### PR TITLE
Suyogmahajan

### PR DESCRIPTION
**Pull request by SuyogMahajan**
Fixes #[17]

**Changes:** Added Reset feature in timer so that user can reset it while countdown is going on.

**Screenshots for the change (if any):**

https://user-images.githubusercontent.com/86179143/195438704-5beb818f-9a8c-4bb3-8276-a8e86afd33c2.mp4

### CODE REVIEW

**Comment by SuyogMahajan** [comment]
Hey @Apoorva57 please review this PR :)

**Comment by Apoorva57** [comment]
@SuyogMahajan the restart button is working but it seems to have caused another issue. The colour of the circular progress bar is not resetting back to green, so kindly look into it.
Capture

**Comment by SuyogMahajan** [comment]
#Demo

https://user-images.githubusercontent.com/86179143/195944070-c0775109-9bf0-4790-a9de-13935cbed462.mp4

#Issue  
#17 

Hey @Apoorva57  please review and merge it , I fixed it now :)

**Review by Apoorva57 — APPROVED** [review]
All issues are cleared now @SuyogMahajan , merging

**Pull request merged**
